/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JavaVisualWindow;

/**
 *
 * @author kh3laghar
 */

import java.sql.PreparedStatement;
import java.sql.ResultSet;
public class Login_Window extends javax.swing.JPanel {
    private static final long serialVersionUID = 1L;
private connection connect=null;
ResultSet rs=null;
PreparedStatement pst=null;
    /**
     * Creates new form Login_Window
     */
    public Login_Window() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmd_login_panel = new javax.swing.JPanel();
        input_username = new javax.swing.JLabel();
        User_name_input = new javax.swing.JTextField();
        password_input = new javax.swing.JLabel();
        password_box = new javax.swing.JPasswordField();
        cmd_login = new javax.swing.JButton();
        cmd_cancel = new javax.swing.JButton();
        image_box = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14), new java.awt.Color(0, 0, 255))); // NOI18N
        setPreferredSize(new java.awt.Dimension(786, 565));

        cmd_login_panel.setBackground(new java.awt.Color(204, 204, 255));
        cmd_login_panel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "LOGIN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Purisa", 1, 12), new java.awt.Color(0, 0, 255)))); // NOI18N

        input_username.setForeground(new java.awt.Color(0, 0, 0));
        input_username.setText("    USER");

        password_input.setForeground(new java.awt.Color(0, 0, 0));
        password_input.setText("PASSWORD");

        password_box.setText("jPasswordField1");

        cmd_login.setText("Login");
        cmd_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_loginActionPerformed(evt);
            }
        });

        cmd_cancel.setText("Cancel");

        javax.swing.GroupLayout cmd_login_panelLayout = new javax.swing.GroupLayout(cmd_login_panel);
        cmd_login_panel.setLayout(cmd_login_panelLayout);
        cmd_login_panelLayout.setHorizontalGroup(
            cmd_login_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cmd_login_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cmd_login_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(password_input, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(input_username, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(53, 53, 53)
                .addGroup(cmd_login_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(User_name_input)
                    .addComponent(password_box, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                    .addGroup(cmd_login_panelLayout.createSequentialGroup()
                        .addComponent(cmd_login)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmd_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        cmd_login_panelLayout.setVerticalGroup(
            cmd_login_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cmd_login_panelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(cmd_login_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(input_username, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(User_name_input, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cmd_login_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password_input, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(password_box, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(cmd_login_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmd_login)
                    .addComponent(cmd_cancel))
                .addContainerGap(114, Short.MAX_VALUE))
        );

        image_box.setBackground(new java.awt.Color(0, 0, 0));
        image_box.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JavaVisualWindow/Login.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(image_box, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmd_login_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(image_box, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(cmd_login_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmd_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_loginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmd_loginActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField User_name_input;
    private javax.swing.JButton cmd_cancel;
    private javax.swing.JButton cmd_login;
    private javax.swing.JPanel cmd_login_panel;
    private javax.swing.JLabel image_box;
    private javax.swing.JLabel input_username;
    private javax.swing.JPasswordField password_box;
    private javax.swing.JLabel password_input;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the connect
     */
    public connection getConnect() {
        return connect;
    }

    /**
     * @param connect the connect to set
     */
    public void setConnect(connection connect) {
        this.connect = connect;
    }
}
